apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: app-02
  annotations:
    nginx.ingress.kubernetes.io/upstream-hash-by: ""
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app-02
            pathType: Prefix
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80
