apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-demo
  namespace: nginx-app01
  annotations:
    nginx.ingress.kubernetes.io/upstream-hash-by: ""
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Connection: close";
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /nginx-app01
            pathType: Prefix
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80
